### ISSUE TITLE
Aggregate error wrapper like map/mapSeries

### ISSUE THREAD

**Issue by innermatrix** [nicolas-van/modern-async#14]
**Please explain the feature or improvement you would like:**

I'd like to see a variant of `forEach`/`forEachSeries` which completes all items (rather than cancelling on first failure), collects all errors (rather than failing on the first), and rejects with an `AggregateError` (if more than one failed? or even if just one failed?)

**Please describe the use case where you would need that feature (the general situation or type of program where that would be helpful):**

I find myself using this pattern a lot when writing some types of backend batch processing code:

```
var errors = [];
for (…) {
  try {
    // Do some async work
  catch(err) {
    errors.push(err)
  }
}

if (errors.length) {
  throw new AggregateError(errors);
}
```

**Please explain why you think that feature would be helpful to other people:**

I imagine I am not the only one trying to handle partial failures in a backend 🙂

**Comment by nicolas-van** [comment]
A very similar request, for the same kind of use case, has already been asked here: https://github.com/nicolas-van/modern-async/issues/9 .

I close this issue as duplicate.
