### ISSUE TITLE
tsc error "library may need to update its package.json"

### ISSUE THREAD

**Issue by innermatrix** [nicolas-van/modern-async#16]
**Describe the bug**

Getting the following error from `tsc`:

```
file.ts:4:23 - error TS7016: Could not find a declaration file for module 'modern-async'. 'node_modules/modern-async/src/modern-async.mjs' implicitly has an 'any' type.
  There are types at 'node_modules/modern-async/modern-async.d.ts', but this result could not be resolved when respecting package.json "exports". The 'modern-async' library may need to update its package.json or typings.

import { sleep } from 'modern-async';
```

**To Reproduce**

Any import from `modern-async`

**Expected behavior**

No error

**Additional context**

I believe this only happens under ESM with TypeScript 5. 

Fix should be as simple as adding the correct value in `export.types` in `package.json`.

https://stackoverflow.com/questions/57383049/typescript-esnext-compiler-option-destroys-es6-import-from-external-lib

**Comment by innermatrix** [comment]
(I see now that this is fixed in `master` so my request now is to get a new version out)

**Comment by nicolas-van** [comment]
Version 1.1.4 has been published with that fix
