### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by VeryCrazyDog** [nicolas-van/modern-async#2]
**Please explain the feature or improvement you would like:**
TypeScript type support, mainly the type declaration.

**Please describe the use case where you would need that feature (the general situation or type of program where that would be helpful):**
For projects that use TypeScript, type declaration is needed for type checking and autocomplete.

**Please explain why you think that feature would be helpful to other people:**
A lot of projects are using and migrating to TypeScript. For example, Visual Studio Code is using TypeScript.

**If you know another library similar to this one that already propose that feature please provide a link:**
- [native-promise-util](https://www.npmjs.com/package/native-promise-util), I am the maintainer of it :)
- [promise-fun](https://github.com/sindresorhus/promise-fun#packages)

**Comment by nicolas-van** [comment]
Hello.

I was already considering this feature in a "not too far future". So yes, it will be done eventually.

On the other hand, if you are already skillful in writing type declarations, proposing them in a pull request will probably get it done quicker than if we have to wait I have some time to make them ^^

**Comment by VeryCrazyDog** [comment]
The library is actually quite new, just curious, why not write in TypeScript in the first place?

On the other hand, will you consider to migrate to TypeScript rather than only adding type declaration on top?

**Comment by nicolas-van** [comment]
Yeah... You're aware that not everyone thinks that Typescript is the language of the future right ? (Or a better language,... or a good language,... or ... a language) 😆

But enough with programming language trolling 😀. No, it won't rewritten in Typescript. Just adding type definitions would be good enough.

**Comment by nicolas-van** [comment]
Has been published in version 2.0.0 .

**Comment by homerjam** [comment]
I think the types are excluded in the `files` when published!

And just to join in with the thread! FWIW I hated typescript, I thought it wasted a lot of time, depending on the project that can still be the case. But as soon as you have a larger more complex project I can honestly say it saves time.

It's hard to justify a rewrite but if I were starting anything new I would certainly use Typescript. There's really no argument against it in modern development, when was the last time you worked on anything without some sort of compilation or build step.

**Comment by nicolas-van** [comment]
It's fixed.

**Comment by homerjam** [comment]
👏
