### ISSUE TITLE
Interrupted iteration is not propagated through `asyncGeneratorMap`

### ISSUE THREAD

**Issue by erpheus** [nicolas-van/modern-async#21]
**Describe the bug**
When iterating through an async iterable that needs to close resources (a db connection, a file, ...) and that has been wrapped in `asyncGeneratorMap` to transform its output, if iteration is not finished that signal is not propagated to the original iterable.

Concretely it seems like asyncIterables have `return` and `throw` [methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGenerator#instance_methods), apart from `next`, and when those are called they should call the same methods of the asyncIterable that was wrapped.

**To Reproduce**

```typescript
import { asyncGeneratorMap } from 'modern-async';

async function *giveMeNumbers(): AsyncIterable<number> {
  console.log('open db connection');
  try {
    for (const element of [1,2,3,4,5,6,7,8,9,0]) {
      yield element;
    }
  } finally {
    console.log('close db connection');
  }
}

async function main() {
  console.log('main start');
  const numbers = giveMeNumbers();
  const doubleNumbers = asyncGeneratorMap(numbers, n => n*2);
  for await (const n of doubleNumbers) {
    console.log('number', n);
    if (n === 4) {
      throw new Error('something happened in the app');
    }
  }
  console.log('main end');
}

main()
```

The output for that program is:

```
main start
open db connection
number 2
number 4
```
(note that "close db connection" doesn't print)

**Expected behavior**

I expect the output to be the same as this working program that does not use the library:

```typescript
async function *giveMeNumbers(): AsyncIterable<number> {
  console.log('open db connection');
  try {
    for (const element of [1,2,3,4,5,6,7,8,9,0]) {
      yield element;
    }
  } finally {
    console.log('close db connection');
  }
}

async function* simpleMapIterable<T, R>(iterable: AsyncIterable<T>, callback: (item: T) => R): AsyncIterable<R> {
  for await (const item of iterable) {
    yield callback(item);
  }
}

async function main2() {
  console.log('main2 start');
  const numbers = giveMeNumbers();
  const doubleNumbers = simpleMapIterable(numbers, n => n*2);
  for await (const n of doubleNumbers) {
    console.log('number', n);
    if (n === 4) {
      throw new Error('something happened in the app');
    }
  }
  console.log('main2 end');
}

main2()
```

output:

```
main2 start
open db connection
number 2
number 4
close db connection
```

**Environment:**
 - Browser and Node
 - Version 2.0.0

**Additional context**
This might affect other methods too, I haven't tried it.

**Comment by nicolas-van** [comment]
Fix was made and published in version 2.0.2. Thank you for the bug report.
